### ISSUE TITLE
Some improvements to the readme.md

### ISSUE THREAD

**Issue by DanKaplanSES** [RafalWilinski/serverless-puppeteer-layers#11]
First time browsing this page and I'm a little confused.  If I have these questions, I think others may, and if they're answered in the readme there could be more adoption:

Does this ONLY take screenshots, or is it more than that?

When it takes a screenshot, where does the screenshot go?  

When you say, `or apply this ARN to your function directly`, is this an alternative to the previous command, or *all* the proceeding information?  I think it's saying, "You can just use this library as a public layer so you don't need to download the repo."

I don't understand why there is a section called `Bundling latest Chromium on your own`.  When and why would I need to do this step?  What does it accomplish?

Since this is for a Lambda (or serverless), why do I need an npm step at all?  Is this just to test it locally?

**Comment by RafalWilinski** [comment]
> Does this ONLY take screenshots, or is it more than that?

"This project **example** returns a screenshot of page requested via `?address=` query parameter." 
While this EXAMPLE is taking only screenshots, _layer_ can serve variety of other purposes.

> When it takes a screenshot

"returns a screenshot of page" - I think It's natural to assume as soon as it loads fully.

> where does the screenshot go? 

Just like shown in the GIF, it's send as a response.

> When and why would I need to do this step? What does it accomplish?

Software evolves. Imagine a new version of Chromium is released which is incompatible with latest Puppeteer and you desperately want to use it. I might be not super eager to update the layer I provide so you might build and deploy your own layer on your own.

> why do I need an npm step at all?

Well, you can use `yarn` alternatively. I think it's kinda normal that you need to install dependencies before deploying, that's common part of most engineering projects.

> Is this just to test it locally?

No. 

If you think this readme is unclear, feel free to submit a PR to improve it.
