### ISSUE TITLE
Binary Media Types

### ISSUE THREAD

**Issue by pwagener** [RafalWilinski/serverless-puppeteer-layers#4]
This repo is a great example of getting Layers , Puppeteer, and Serverless wired up -- thanks for putting it together.  However I'm unable to get it working smoothly without making a single line change:

```
$ git diff serverless.yml
diff --git a/serverless.yml b/serverless.yml
index b17ea9c..73c08e9 100644
--- a/serverless.yml
+++ b/serverless.yml
@@ -12,7 +12,7 @@ plugins:
 custom:
   apigwBinary:
     types:
-      - 'image/png'
+      - '*/*'
 
 functions:
   puppeteer-orchestrator:
```

Without setting the binary media type to `*/*`, API Gateway does not decode the `base64` string into binary for me... so I just get the encoded string.  Am I missing something?

**Comment by RafalWilinski** [comment]
Yes, you're right! I've changed that manually and that it worked for me. Changing...
